### ISSUE TITLE
How do i do this with deep query?

### ISSUE THREAD

**Issue by dlsagayaraj** [mmckegg/json-query#25]
var data = {
        grouped_people: {
            'friends': [
                {name: 'Steve', country: ['NZ','US']},
                {name: 'Daniel', country: ['NZ']},
                {name: 'Bob', country: ['US']}
            ],
            'enemies': [
                {name: 'Evil Steve', country: ['NZ','US']}
            ]
        }
    }

I want to get all people who has country 'US' which will be Steve,Bob,Evil Steve .
How do i query this in with deep query?

i tried  jsonQuery('grouped_people[][][*country=US]', {data: data})

**Comment by mmckegg** [comment]
You were on the right track. The reason this wasn't working is because `[]` only works properly with returning single results, not collections. It will stop continuing to the next collection when it finds one result. 

I have just added a much improved way of doing deep queries using `[**]` in **v2.2.0**. It works much more like you'd expect. It just flattens on object and its key-values into an array, then you can use any query on it to filter.

In the latest version, do this:

```js
jsonQuery('grouped_people[**][*country~US]', { data: data }).value
```
