### ISSUE TITLE
Please add more example to README file, and help me on this

### ISSUE THREAD

**Issue by dehghani-mehdi** [mmckegg/json-query#40]
Hello, thanks for your awesome job.

How I can use `OR` syntax and `Query Params` together?

My json:

```
[{"Domain":"ABC","Username":"A","Password":"1"},{"Domain":"ABCD","Username":"AB","Password":"2"}]
```

Following works as expected:

```js
var data = { obj: json }; // json is above json!
var q = 'A';    
var r = jsonQuery(['obj[*Username~?]', q], {
    data: data
});
```

But this one not:

```
var r = jsonQuery(['obj[*Username~?]|obj[*Domain~?]', q], {
    data: data
});
```

I tired some other options too, but no success.

Thank you.
Mehdi

**Comment by Clifra-Jones** [comment]
Well I assume you mean an = instead of ~ but I cannot get this to work
let obj = jsonQuery(['Materials[MATERIAL=?]', mat], { data: jsonMaterials});
I do not seem to be able to get this to work at all with a variable as the partameter.
This works
let obj = jsonQuery(['Materials[MATERIAL=?]', 'SULPHUR'], { data: jsonMaterials});

**Comment by dehghani-mehdi** [comment]
R.I.P
